"use client";

import { motion, useReducedMotion } from "framer-motion";
import { interactionClasses } from "@/lib/interaction-classes";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useLayoutEffect, useRef } from "react";
gsap.registerPlugin(ScrollTrigger);
const pillars = [["01", "Diagnose", "Finds what’s actually wrong, with evidence.", ["Broken imports", "Dead files", "Hardcoded secrets", "Weak tests"]], ["02", "Explain", "Shows why it matters, in plain language.", ["Severity", "Confidence", "Affected files", "Root cause"]], ["03", "Repair", "Fixes one issue at a time, safely.", ["Isolated working copy", "Readable diff", "Your approval required", "Full verification"]]] as const;
export function WhatWeDo() { const reduceMotion = useReducedMotion(); const sectionRef = useRef<HTMLElement>(null); useLayoutEffect(() => { if (reduceMotion || !sectionRef.current) return; const context = gsap.context(() => { const cards = gsap.utils.toArray<HTMLElement>(".pillar-card"); gsap.set(cards, { scale: 1, opacity: 1 }); ScrollTrigger.matchMedia({ "(min-width: 1024px)": () => cards.map((card, index) => { const next = cards[index + 1]; if (!next) return; return gsap.to(card, { scale: .95, opacity: .7, ease: "none", scrollTrigger: { trigger: next, start: "top 55%", end: "top top+=112", scrub: .7, invalidateOnRefresh: true } }); }) }); }, sectionRef); return () => context.revert(); }, [reduceMotion]); return <section ref={sectionRef} id="features" className="relative mx-auto max-w-7xl px-5 py-24 lg:px-8"><motion.div className="relative z-10" initial={reduceMotion ? false : { opacity: 0, y: 24 }} whileInView={reduceMotion ? {} : { opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .65 }}><p className="font-mono text-xs uppercase tracking-[.16em] text-accent">Clinical approach</p><h2 className="mt-4 max-w-2xl text-4xl font-bold tracking-[-.04em] sm:text-5xl">Not just another AI code reviewer.</h2></motion.div><div className="relative z-10 mt-12 flex flex-col gap-5 lg:mx-auto lg:max-w-3xl">{pillars.map(([number, title, description, bullets], index) => <motion.article key={title} style={{ zIndex: index + 1 }} className={`pillar-card ${interactionClasses.hoverCard} rounded-lg border border-accent/15 bg-background-elevated p-7 shadow-lg shadow-black/10 lg:sticky lg:top-28`} initial={reduceMotion ? false : { opacity: 0, y: 24 }} whileInView={reduceMotion ? {} : { opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .65, delay: index * .1 }}><span className="font-mono text-sm text-accent">{number}</span><h3 className="mt-8 text-2xl font-bold">{title}</h3><p className="mt-3 leading-7 text-text-muted">{description}</p><ul className="mt-7 space-y-2 border-t border-accent/15 pt-5">{bullets.map((bullet) => <li key={bullet} className="font-mono text-xs"><span className="mr-2 text-accent">↗</span>{bullet}</li>)}</ul></motion.article>)}</div></section>; }
