import './style.css';
import { apiConfigured, repositoryApi } from './lib/api';
import type { ApiError } from './lib/types';

const app = document.querySelector<HTMLDivElement>('#app');
if (!app) throw new Error('Application root not found.');
const diagnoses = [
  { severity: 'critical', title: 'Unbounded retry loop can exhaust API quota', path: 'src/jobs/sync.ts:84', confidence: '98%', detail: 'A failed upstream request re-enters the retry branch without a maximum attempt guard.' },
  { severity: 'warning', title: 'Authentication boundary is repeated in routes', path: 'src/routes/projects.ts:12–58', confidence: '92%', detail: 'Three handlers perform equivalent token parsing; a shared middleware would reduce drift.' },
  { severity: 'info', title: 'Test coverage does not include failed webhooks', path: 'tests/webhooks.test.ts', confidence: '81%', detail: 'The error response path has no direct assertion.' }
];
app.innerHTML = `
<a class="skip" href="#main">Skip to content</a>
<header class="topbar"><a class="brand" href="#top" aria-label="Repo Doctor home"><span class="brand-mark">R</span>Repo Doctor</a><nav aria-label="Main navigation"><a href="#how">How it works</a><a href="#sample">Sample report</a><a class="nav-cta" href="#connect">Examine a repository ↗</a></nav></header>
<main id="main">
<section class="hero" id="top"><div class="eyebrow"><span class="pulse"></span> Evidence-first codebase care</div><h1>Your codebase has symptoms.<br><em>Find the cause.</em></h1><p class="lede">Repo Doctor examines the structure behind a messy repository, explains what it found, and proposes repairs you can inspect before anything changes.</p><div class="hero-actions"><a class="button primary" href="#connect">Start an examination →</a><a class="button ghost" href="#sample">Explore a sample report</a></div><p class="trust"><span>✓</span> Read-only examination · Human approval before treatment · Verification included</p></section>
<section class="record-preview" aria-labelledby="record-title"><div class="record-head"><div><p class="overline">Sample health record</p><h2 id="record-title">northstar-api <span class="branch">main</span></h2><p>TypeScript · Node 20 · 214 files examined</p></div><div class="score"><span>Health score</span><strong>72</strong><small>Needs attention</small></div></div><div class="score-grid"><div><span>Architecture</span><b>84</b><i style="--value:84%"></i></div><div><span>Reliability</span><b>61</b><i style="--value:61%"></i></div><div><span>Quality</span><b>76</b><i style="--value:76%"></i></div><div><span>Security</span><b>88</b><i style="--value:88%"></i></div></div><div class="record-footer"><span><b class="critical-dot"></b> 1 needs immediate attention</span><span><b class="warning-dot"></b> 4 treatments available</span><a href="#sample">View report →</a></div></section>
<section class="connect section" id="connect"><div class="section-copy"><p class="overline">Begin safely</p><h2>Connect a repository.<br>We’ll do the listening.</h2><p>Submit a public GitHub URL to start an examination. Repo Doctor validates the source before it reads anything.</p><ul class="check-list"><li>Repository contents are never changed during examination</li><li>Every treatment is shown as a diff before approval</li><li>Verification results stay with the treatment record</li></ul></div><form class="intake" id="intake" novalidate><label for="repository">Public GitHub repository URL</label><div class="input-row"><input id="repository" type="url" inputmode="url" autocomplete="url" placeholder="https://github.com/owner/repository" aria-describedby="connection-note form-status" required><button class="button primary" type="submit">Validate repository</button></div><p id="connection-note">Private repositories and ZIP upload require a configured backend.</p><div id="form-status" class="form-status" aria-live="polite"></div><div class="backend-note ${apiConfigured ? 'ready' : ''}"><span>${apiConfigured ? '●' : '○'}</span><div><b>${apiConfigured ? 'Backend connected' : 'Backend not configured'}</b><p>${apiConfigured ? 'Submissions will be sent to the configured service.' : 'This interface is ready to integrate, but no analysis service exists in this project yet.'}</p></div></div></form></section>
<section class="how section" id="how"><div class="section-heading"><p class="overline">A visible chain of care</p><h2>Nothing happens off the record.</h2><p>Each decision has evidence, a scope, and a next step.</p></div><ol class="steps"><li><span>01</span><h3>Examine</h3><p>Map technologies, dependencies, imports, tests, and documentation.</p></li><li><span>02</span><h3>Diagnose</h3><p>Prioritize causes with file-level evidence and confidence.</p></li><li><span>03</span><h3>Propose</h3><p>Generate a bounded treatment with assumptions and risk.</p></li><li><span>04</span><h3>Verify</h3><p>Run formatting, linting, types, tests, and build checks.</p></li></ol></section>
<section class="sample section" id="sample"><div class="sample-title"><div><p class="overline">Sample report · illustrative only</p><h2>A diagnosis should explain itself.</h2></div><span class="sample-chip">Northstar API</span></div><div class="report-layout"><div class="diagnoses"><div class="report-toolbar"><b>3 diagnoses</b><label class="search">⌕<input id="diagnosis-search" type="search" placeholder="Search diagnoses" aria-label="Search sample diagnoses"></label></div><div id="diagnosis-list">${diagnoses.map((item, index) => `<button class="diagnosis ${index === 0 ? 'selected' : ''}" data-index="${index}"><span class="severity ${item.severity}"></span><span class="diagnosis-main"><b>${item.title}</b><small>${item.path}</small></span><span class="confidence">${item.confidence}</span></button>`).join('')}</div></div><aside class="evidence" aria-live="polite"><p class="overline">Diagnosis</p><div id="evidence-content"></div></aside></div></section>
<section class="treatment section"><div><p class="overline">Treatment review</p><h2>Show the change. Then ask.</h2><p>A repair is never applied to your repository. It is prepared in an isolated copy, reviewed as a file-level diff, then verified after explicit approval.</p><a href="#connect" class="text-link">See the approval workflow →</a></div><div class="diff-card"><div class="diff-head"><div><b>src/jobs/sync.ts</b><span>1 file · +6 −1</span></div><span class="risk">Low risk</span></div><pre aria-label="Sample code change"><code><span class="muted">84</span> <span class="del">- while (shouldRetry(error)) retry();</span>\n<span>84</span> <span class="add">+ for (let attempt = 0; attempt &lt; MAX_RETRIES; attempt++) {</span>\n<span>85</span> <span class="add">+   if (!(await retry(error, attempt))) break;</span>\n<span>86</span> <span class="add">+ }</span></code></pre><div class="verification"><span><b>✓</b> Type check</span><span><b>✓</b> Tests</span><span><b>✓</b> Build</span></div></div></section>
<section class="final-cta"><p class="overline">Keep developers in control</p><h2>Make the next repair<br>the safest one.</h2><a class="button light" href="#connect">Examine a repository →</a></section>
</main><footer><a class="brand" href="#top"><span class="brand-mark">R</span>Repo Doctor</a><span>Repository health, explained.</span><span>© 2026</span></footer>`;
const evidence = document.querySelector<HTMLDivElement>('#evidence-content');
function showDiagnosis(index: number) { const diagnosis = diagnoses[index]; if (!evidence) return; evidence.innerHTML = `<h3>${diagnosis.title}</h3><p>${diagnosis.detail}</p><dl><div><dt>Confidence</dt><dd>${diagnosis.confidence}</dd></div><div><dt>Repairability</dt><dd>Available</dd></div><div><dt>Risk</dt><dd>Low</dd></div></dl><div class="evidence-file"><span>Evidence</span><code>${diagnosis.path}</code><p>Review the highlighted source before generating a treatment.</p></div><button class="button disabled" type="button" disabled>Generate treatment</button><small class="honest-note">Available when a backend is connected.</small>`; document.querySelectorAll<HTMLButtonElement>('.diagnosis').forEach((button) => button.classList.toggle('selected', Number(button.dataset.index) === index)); }
showDiagnosis(0);
document.querySelectorAll<HTMLButtonElement>('.diagnosis').forEach((button) => button.addEventListener('click', () => showDiagnosis(Number(button.dataset.index))));
document.querySelector<HTMLInputElement>('#diagnosis-search')?.addEventListener('input', (event) => { const query = (event.target as HTMLInputElement).value.toLowerCase(); document.querySelectorAll<HTMLButtonElement>('.diagnosis').forEach((button) => { button.hidden = !button.textContent?.toLowerCase().includes(query); }); });
document.querySelector<HTMLFormElement>('#intake')?.addEventListener('submit', async (event) => { event.preventDefault(); const input = document.querySelector<HTMLInputElement>('#repository'); const status = document.querySelector<HTMLDivElement>('#form-status'); if (!input || !status) return; const url = input.value.trim(); if (!/^https:\/\/github\.com\/[\w.-]+\/[\w.-]+\/?$/.test(url)) { status.className = 'form-status error'; status.textContent = 'Enter a public GitHub repository URL in the form github.com/owner/repository.'; input.focus(); return; } if (!apiConfigured) { status.className = 'form-status error'; status.textContent = 'Cannot begin an examination: no backend URL has been configured.'; return; } status.className = 'form-status'; status.textContent = 'Validating repository…'; try { const exam = await repositoryApi.submit({ source: 'github', url }); status.className = 'form-status success'; status.textContent = `Examination ${exam.id} created. Live progress will appear when this endpoint is connected.`; } catch (error) { const apiError = error as ApiError; status.className = 'form-status error'; status.textContent = apiError.message || 'Unable to validate the repository. Please try again.'; } });
